[build]
  command = "pnpm run build"
  publish = "build/client"

[dev]
  command = "pnpm run dev"
  port = 5173

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 